# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Ultra-fast build optimizations
ENV['FAST_BUILD'] = 'true'
ENV['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
ENV['GCC_OPTIMIZATION_LEVEL'] = '0'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'thekkabazar' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'thekkabazarTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # ULTRA-FAST iOS Build Optimizations
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable all optimizations for maximum speed
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        config.build_settings['SWIFT_COMPILATION_MODE'] = 'singlefile'
        
        # Disable index store for faster builds
        config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
        config.build_settings['SWIFT_INDEX_STORE_ENABLE'] = 'NO'
        
        # Disable debugging symbols for speed
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
        config.build_settings['COPY_PHASE_STRIP'] = 'YES'
        
        # Enable parallel builds
        config.build_settings['SWIFT_WHOLE_MODULE_OPTIMIZATION'] = 'NO'
        config.build_settings['SWIFT_USE_PARALLEL_WHOLE_MODULE_OPTIMIZATION'] = 'NO'
        
        # Disable unnecessary features
        config.build_settings['ENABLE_TESTABILITY'] = 'NO'
        config.build_settings['SWIFT_EMIT_LOC_STRINGS'] = 'NO'
      end
    end
  end
end
