import {StyleSheet} from 'react-native';
import {colors, fonts} from '../../theme';

const styles = StyleSheet.create({
  HomeContainer: {
    backgroundColor: colors.background,
    flex: 1,
  },
  navcontainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    height: '100px',
    backgroundColor: colors.white,
  },
  iconsContainer: {
    flexDirection: 'row',
    width: '25%',
  },
  logo: {
    width: 85,
    objectFit: 'contain',
    aspectRatio: 2 / 1,
  },
  searchSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    width: '100%',
    height: 45,
    marginTop: 4,
    marginLeft: 10,
    borderColor: colors.gray,
    borderWidth: 1,
  },
  searchIcon: {
    padding: 10,
  },
  input: {
    flex: 1,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 0,
    marginLeft: 10,
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: '#fff',
    color: '#424242',
  },
  modalContainer: {
    height: '80%',
    backgroundColor: colors.white,
    bottom: 0,
    right: 0,
    left: 0,
    position: 'absolute',
  },
  modalContent: {
    width: '100%',
    padding: 15,
  },
  modalText: {
    color: colors.primary,
    fontFamily: fonts.regular,
    textAlign: 'left',
    lineHeight: 28,
    fontSize: 24,
  },
  dropdown1BtnStyle: {
    width: '100%',
    height: 50,
    backgroundColor: colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4D4D4',
    marginBottom: 15,
  },
  dropdown1BtnTxtStyle: {color: '#444', textAlign: 'left'},
  dropdown1RowStyle: {backgroundColor: '#EFEFEF', borderBottomColor: '#C5C5C5'},
  dropdown1RowTxtStyle: {color: '#444', textAlign: 'left'},
  dropdown1SelectedRowStyle: {backgroundColor: 'rgba(0,0,0,0.1)'},
  dropdown1searchInputStyleStyle: {
    backgroundColor: '#EFEFEF',
    borderRadius: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#444',
  },
  searchInput: {
    width: '100%',
    height: 50,
    backgroundColor: colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4D4D4',
    marginBottom: 15,
    fontSize: 18,
    padding: 15,
    color: 'black',
  },
  titletext: {
    fontSize: 14,
    color: colors.white,
    fontFamily: fonts.regular,
    backgroundColor: colors.text,
    padding: 10,
    width: 95,
    height: 35,
    borderRadius: 20,
    textAlign: 'center',
    marginBottom: 10,
  },
  Card: {
    backgroundColor: colors.white,
    display: 'flex',
    flexDirection: 'row',
    margin: 10,
    padding: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 15,
  },
  image: {
    height: 300,
    width: 120,
    resizeMode: 'contain',
  },
  CardText: {
    color: '#000',
    fontSize: 14,
    marginLeft: 8,
    flex: 1,
  },
  CardHeading: {
    display: 'flex',
    flexDirection: 'row',
  },
  Cardbodytext: {
    display: 'flex',
    flexDirection: 'row',
    // justifyContent: 'space-between',
    // flexGrow: 1,
    flexWrap: 'wrap',
  },
  cusBottom: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    backgroundColor: colors.white,
    borderRadius: 8,
    marginTop: 10,
    height: 50,
    borderWidth: 1,
    borderColor: colors.gray,
    shadowOffset: {
      width: 1,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  CardFooter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 2,
    borderTopColor: '#C6C1C1',
    padding: 10,
    marginTop: 10,
    alignItems: 'center',
  },
  Icons: {
    color: colors.primary,
    marginLeft: 20,
  },
  datepicker: {
    width: '100%',
    height: 50,
    backgroundColor: colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4D4D4',
    marginBottom: 15,
    color: 'black',
    padding: 15,
    fontSize: 18,
    textAlign: 'left',
  },
});

export default styles;
