import {StyleSheet} from 'react-native';
import {colors, fonts} from '../../theme';

const styles = StyleSheet.create({
  HomeContainer: {
    backgroundColor: colors.background,
    flex: 1,
  },
  navcontainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    height: '100px',
    backgroundColor: colors.background,
  },
  iconsContainer: {
    flexDirection: 'row',
    width: '25%',
  },
  logo: {
    width: 85,
    objectFit: 'contain',
    aspectRatio: 2 / 1,
  },
  searchSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    width: '65%',
    height: 45,
    marginTop: 4,
    marginLeft: 20,
    borderColor: colors.gray,
    borderWidth: 1,
  },
  searchIcon: {
    padding: 10,
  },
  input: {
    flex: 1,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 0,
    marginLeft: 10,
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: '#fff',
    color: '#424242',
  },
  modalContainer: {
    height: '100%',
    backgroundColor: colors.white,
    bottom: 0,
    right: 0,
    left: 0,
    position: 'absolute',
  },
  modalContent: {
    width: '100%',
    padding: 15,
  },
  modalText: {
    color: colors.primary,
    fontFamily: fonts.regular,
    textAlign: 'left',
    lineHeight: 28,
    fontSize: 24,
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 1,
  },
  dropdown1BtnStyle: {
    width: '100%',
    height: 50,
    backgroundColor: colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4D4D4',
    marginBottom: 15,
  },
  dropdown1BtnTxtStyle: {color: '#444', textAlign: 'left'},
  dropdown1RowStyle: {
    backgroundColor: colors.white,
    borderBottomColor: '#E5E5E5',
    padding: 12,
    borderBottomWidth: 1,
  },
  dropdown1RowTxtStyle: {
    color: '#333',
    textAlign: 'left',
    fontSize: 14,
    fontWeight: '400',
  },
  dropdown1SelectedRowStyle: {
    backgroundColor: '#F0F7FF',
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  dropdown1searchInputStyleStyle: {
    backgroundColor: colors.white,
    borderRadius: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
    padding: 12,
    fontSize: 14,
  },
  dropdown1DropdownStyle: {
    backgroundColor: colors.white,
    borderRadius: 8,
    marginTop: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  searchInput: {
    width: '100%',
    height: 50,
    backgroundColor: colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4D4D4',
    marginBottom: 15,
    fontSize: 18,
    padding: 15,
    color: 'black',
  },
  titletext: {
    fontSize: 14,
    color: colors.white,
    fontFamily: fonts.regular,
    backgroundColor: colors.text,
    padding: 10,
    width: 95,
    height: 35,
    borderRadius: 20,
    textAlign: 'center',
    marginBottom: 10,
  },
  Card: {
    backgroundColor: colors.white,
    display: 'flex',
    flexDirection: 'row',
    margin: 10,
    padding: 10,
    borderRadius: 5,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 15,
  },
  image: {
    height: 200,
    width: 100,
    resizeMode: 'contain',
  },
  CardText: {
    color: '#000',
    fontSize: 14,
    marginLeft: 8,
    flex: 1,
  },
  CardHeading: {
    display: 'flex',
    flexDirection: 'row',
  },
  Cardbodytext: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  cusBottom: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '40%',
    backgroundColor: colors.white,
    borderRadius: 8,
    marginTop: 20,
    height: 35,
    borderWidth: 1,
    borderColor: colors.gray,
    shadowOffset: {
      width: 1,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  CardFooter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 2,
    borderTopColor: '#C6C1C1',
    padding: 10,
    marginTop: 10,
    alignItems: 'center',
  },
  Icons: {
    color: colors.primary,
    marginLeft: 20,
  },
  datepicker: {
    width: '100%',
    height: 50,
    backgroundColor: colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4D4D4',
    marginBottom: 15,
    color: 'black',
    padding: 15,
    fontSize: 18,
    textAlign: 'left',
  },
  // Empty State Styles
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#fff',
    minHeight: 400,
  },
  emptyContent: {
    alignItems: 'center',
  },
  emptyIconWrapper: {
    marginBottom: 20,
  },
  emptyIconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyTextWrapper: {
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  emptyDescription: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
  loadingMore: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  clearFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    padding: 10,
    borderRadius: 8,
    width: '48%',
    justifyContent: 'center',
  },
  clearFilterIcon: {
    marginRight: 8,
  },
  clearFilterText: {
    color: '#333',
    fontSize: 16,
  },
  clearDateButton: {
    position: 'absolute',
    right: 10,
    top: 15,
  },
  dateContainer: {
    position: 'relative',
  },
  adContainer: {
    marginVertical: 10,
    marginHorizontal: 15,
    borderRadius: 8,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  adImage: {
    width: '100%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  adOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    padding: 8,
    borderRadius: 4,
  },
  adText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default styles;
